Algoritmo "salario_professores"

Var
nomeProf: caractere
quantidadeHoras, valorHora: real

Inicio
escreva("Digite o nome do professor: ")
leia(nomeProf)

escreva("Digite a quantidade de horas trabalhadas por dia: ")
leia(quantidadeHoras)

escreva("Digite o valor da hora aula: ")
leia(valorHora)

escreva("O professor ", nomeProf, " recebe R$", quantidadeHoras * valorHora, " por dia.")

Fimalgoritmo