Algoritmo "Vetor_frutas"

Var
frutas: vetor[0..7] de caracter
posicao: inteiro

Inicio
escreval("------------------------------------------")
escreval("####### Cadastro de Frutas #######")
escreval

para posicao de 0 ate 7 faca
     escreva("Digite o nome da fruta: ")
     leia(frutas[posicao])
fimpara

escreval("------------------------------------------")
escreval

para posicao de 0 ate 7 faca
     escreval("A ", posicao, "ª fruta informada foi: ", frutas[posicao])
fimpara

Fimalgoritmo